name: app_sales_distribution_web
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  auto_route: ^7.3.2
  awesome_dio_interceptor: ^1.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  dropdown_search: ^5.0.6
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.18.6
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.2
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  mask_text_input_formatter: ^2.4.0
  path_provider: ^2.0.15
  provider: ^6.0.5
  shimmer: ^3.0.0
  url_launcher: ^6.1.11
  uuid: ^3.0.6
dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/image/
    - .env
